import {
    Home,
    User,
    MessageCircle,
    FileText,
    Map,
    Plus,
    Heart,
    Edit,
    Trash,
    MapPin,
    Inbox,
    Camera,
    Facebook,
    Instagram,
    Twitter,
    Linkedin,
    Globe,
    Briefcase,
    Smile,
    Sparkles,
    UserX,
    ChevronLeft,
    MoreVertical,
    Image as ImageIcon,
    LucideIcon,
    X,
    Hand
} from 'lucide-react-native';

import CustomExample from './icons/custom-example.svg';

export const Icons = {
    Home,
    User,
    MessageCircle,
    Posts: FileText,
    Map,
    Plus,
    Heart,
    Edit,
    Trash,
    Location: MapPin,
    Inbox,
    Camera,
    Facebook,
    Instagram,
    Twitter,
    Linkedin,
    Website: Globe,
    Work: Briefcase,
    Male: Smile,
    Female: Smile,
    Other: Sparkles,
    Secret: UserX,
    Back: ChevronLeft,
    More: MoreVertical,
    Image: ImageIcon,
    Close: X,
    Greeting: Hand,
    CustomExample: CustomExample
};

export type { LucideIcon };
